# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master
pool:
  vmImage: 'windows-latest'
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $ProjectJsonObject = (Get-Content $(ProjectJsonPath)) -join "`n" | ConvertFrom-Json
      $ProjectVersion =$ProjectJsonObject.projectVersion
      
      $projectVersionTokens = $ProjectVersion.Split(".")
      $major = $projectVersionTokens[0]
      $minor = $projectVersionTokens[1]
      $revNumber = git rev-list HEAD --count
      
      Write-Output ("##vso[task.setvariable variable=Major;]$major")
      Write-Output ("##vso[task.setvariable variable=Minor;]$minor")
      Write-Output ("##vso[task.setvariable variable=RevisionNumber;]$revNumber")
      echo $major
      echo $minor
      echo $revNumber
- task: UiPathPackage@1
  inputs:
    packageAction: 'pack'
    versioningType: 'userversion'
    version: '$(Major).$(Minor).$(Build.BuildNumber)'
    platformVersion: '19.10.5'
    uninstallOption: 'ifdifferent'
    outputFolder: '$(Build.ArtifactStagingDirectory)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd C:\Program Files (x86)\UiPath\Studio 
      .\UiPath.Studio.CommandLine.exe analyze -p D:/a/1/s/project.json
      
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'UiPathArtifact'
    publishLocation: 'Container'